// Created by Vladislav Melnikov on 16.12.17.

#ifndef LABTECH_MACRO_COLOR_HPP
#define LABTECH_MACRO_COLOR_HPP

#define COLOR_GHOST 15
#define COLOR_ORANGE 16
#define COLOR_GRAYG 17
#define PAIR_MAIN COLOR_PAIR(1)
#define PAIR_INV COLOR_PAIR(2)
#define PAIR_ERR COLOR_PAIR(3)
#define PAIR_SUC COLOR_PAIR(4)
#define PAIR_FULL_HP COLOR_PAIR(5)
//#define PAIR_MEDIUM_HP COLOR_PAIR(6)
#define PAIR_LOW_HP COLOR_PAIR(7)
#define PAIR_BOMB COLOR_PAIR(8)
#define PAIR_WALL COLOR_PAIR(9)
#define PAIR_TREASURE COLOR_PAIR(6)

#endif //LABTECH_MACRO_COLOR_HPP
